### ISSUE TITLE
Return

### ISSUE THREAD

**Issue by IanaKhitsko** [zvierievkp31ms/MIPZ#8]
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L138

Just 
if (check_diagonals(x, y, true)) {
   return true;
}

**Comment by zvierievkp31ms** [comment]
The result of this function **check_diagonals** is undefined or Result - an object with information about the winner and the starting point of the segment. Therefore, it is necessary to save the implemented code, since the proposed option only provides information about whether to stop the algorithm without the necessary information for further writing to a file.
